{% set name = "algotom" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/algotom-{{ version }}.tar.gz
  sha256: 9b9f8a6fcd8d9ce9b8e6236d6181947d14b26aa3186cda0675c142ca3532417d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - h5py
    - joblib
    - numba >=0.50.1
    - numpy >=1.18
    - pillow
    - python >=3.8
    - pywavelets
    - scipy

test:
  imports:
    - algotom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/algotom/algotom
  summary: 'Data processing algorithms for tomography'
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://algotom.readthedocs.io

extra:
  recipe-maintainers:
    - nghia-vo
