{% set name = "algotom" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/algotom-{{ version }}.tar.gz
  sha256: 1f13682f57a56d06b06c5e969e16ecc04fa8f422c5fec2bf296b91b15509a956

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - h5py
    - joblib
    - numba >=0.50.1
    - numpy >=1.16
    - pillow
    - python >=3.7
    - pywavelets
    - scipy

test:
  imports:
    - algotom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/algotom/algotom
  summary: 'Data processing algorithms for tomography'
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://algotom.readthedocs.io

extra:
  recipe-maintainers:
    - algotom
    - nghia-vo
   
